alter table BOOKSTORE_CUSTOMER add constraint FK_BOOKSTORE_CUSTOMER_ON_USER foreign key (USER_ID) references SEC_USER(ID);
create index IDX_BOOKSTORE_CUSTOMER_ON_USER on BOOKSTORE_CUSTOMER (USER_ID);
