INSERT INTO SYS_SCHEDULED_TASK
(
    ID, CREATE_TS, CREATED_BY, UPDATE_TS, UPDATED_BY, DELETE_TS, DELETED_BY,
    DEFINED_BY, SYS_TENANT_ID, BEAN_NAME, METHOD_NAME, CLASS_NAME, SCRIPT_NAME,
    USER_NAME, IS_SINGLETON, IS_ACTIVE, PERIOD_, TIMEOUT, START_DATE, CRON,
    SCHEDULING_TYPE, TIME_FRAME, START_DELAY, PERMITTED_SERVERS, LOG_START,
    LOG_FINISH, LAST_START_TIME, LAST_START_SERVER, METHOD_PARAMS, DESCRIPTION
)
VALUES
(
    '03cbea49-ab37-9df1-d700-a1b1e13896cf',
    '2024-09-08 23:37:50',
    'admin',
    '2024-09-09 13:57:16',
    'admin',
    NULL,
    NULL,
    'B',
    NULL,
    'bookstore_OrderCheckerBean',
    'checkOrders',
    NULL,
    NULL,
    NULL,
    NULL,
    TRUE,
    10,
    NULL,
    NULL,
    NULL,
    'P',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '<?xml version="1.0" encoding="UTF-8"?>\n\n<params/>',
    NULL
);
