alter table BOOKSTORE_ORDER_LINE add constraint FK_BOOKSTORE_ORDER_LINE_ON_BOOK foreign key (BOOK_ID) references BOOKSTORE_BOOK(ID);
create index IDX_BOOKSTORE_ORDER_LINE_ON_BOOK on BOOKSTORE_ORDER_LINE (BOOK_ID);
