alter table BOOKSTORE_ONLINE_ORDER add constraint FK_BOOKSTORE_ONLINE_ORDER_ON_CUSTOMER foreign key (CUSTOMER_ID) references BOOKSTORE_CUSTOMER(ID);
create index IDX_BOOKSTORE_ONLINE_ORDER_ON_CUSTOMER on BOOKSTORE_ONLINE_ORDER (CUSTOMER_ID);
